# Generated by Django 3.2.3 on 2021-05-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuerequest',
            options={'verbose_name': 'Book Issue Request', 'verbose_name_plural': 'Book Issue Requests'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
